language: python
python:
- 3.6
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dapacruz
  password:
    secure: IFMELL/Pdfr2NNL4iQ91qnXr5IbrGBCW4P1XWaLCwfA4qkK32/dTFSaR1AgMY3I6MIN/YZkU0JxL9xlPmeWxXs7T6TDsBSy3AXt/w4SdS1KF0ATzzX69tVYe9E8Ri0Bg3t4mRyHypdcIrJ0qAvFUX3VzB2XlAmhxomWqDc3JBSEhnKoSIUb7ODiyT8PzVIUXlwjg6dfy61lE8bnvcgPm+X7bS8/MqpvjQlLAhHy+9pwzhRU+HsnTX88NcrlC4UCz91NAxTO6Vx+hfjoUgik7mn7fN+rGDeuXBo/0bNfzolVKCym6MXOMpVPLQrI8Tp2aQmC85XSUBaD24RuMXNzmMiuDxBy1ry4eIsd82BrrGfKpIe/3z5ocggggMPOnkBA7mBMTKmKQPrKB7X/HEl1DmOWaN3aYofwF335uXPSAyg8b6+2sH/cuqE2+iWtatb2R1RtwC8N967zw8+7G9nO7jtuXy1jJnLTtFl15bd0od4Gw2n1iS1XfU/1x2CDYMlJV/3ZjliqOagfo9AJsvFlpFptuoP0xqKdZxjda8m4RWOLIyy2vqfVkLk1NONXacYqn45lXczzqDnzaWS/JLx9nGxa/pthciVC+J1Jddvj0VpEtwl9fJlwTa/YxWPtI1IUjKOSW3up2pyW/QzmqtOENGp2inuizacETeRO8V1rVChM=
  on:
    tags: true
    repo: dapacruz/panw-utils
    python: 3.7
